### ISSUE TITLE
Kyoto Cargo NPC Prices

### ISSUE THREAD

**Issue by Steffbeard** [Steffbeard/RiseOfNationsMC#1]
The sell price of sugarcane is not at a higher value then those of the other trade cities. Please make it higher by about $200.

**Comment by Ethansito** [comment]
I'm sorry, but your request has been denied. If you would like to make a request appeal, please go to this website: http://rightxd.org/666 to file your claim. Thank you, and have a nice day.
                                                                                                              -Chief of Dirty Articles Department,
                                                                                                                Ethansito
